spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/swipescriptdb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
